version: "3.9"


services:
  fake-gcs:
    image: fsouza/fake-gcs-server:latest
    container_name: fake-gcs
    ports:
      - "4443:4443"
    command: >
      -scheme http
      -port 4443
      -external-url http://localhost:4443
      -data /data
    volumes:
      - ./fake-gcs-data:/data


  fake-gcs-init:
    image: curlimages/curl:8.6.0
    depends_on:
      - fake-gcs
    entrypoint: ["/bin/sh", "-c"]
    command: >
      echo "Waiting for fake GCS..." &&
      sleep 3 &&
      curl -X POST "http://fake-gcs:4443/storage/v1/b?project=test-project"
      -H "Content-Type: application/json"
      -d '{"name":"kyc-documents"}' ||
      echo "Bucket already exists"





